### ISSUE TITLE
Homebridge crashes after a while

### ISSUE THREAD

**Issue by AndreWeberHH** [simont77/fakegato-history#59]
I getting the following error after 1-2 minutes after startup.
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:53:11)
    at Buffer.readFloatBackwards [as readFloatBE] (internal/buffer.js:403:5)
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-knx/lib/knxmonitor.js:62:29)
    at Parser.emit (events.js:182:13)
    at /usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:96:12
    at Decoder.decode (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/decoder.js:233:7)
    at Parser.parseTelegram (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:93:18)
    at Parser.onData (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:150:12)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:36:10)
    at Socket.emit (events.js:182:13)

I saw now stats so far.
Still tried to get it running.

**Comment by simont77** [comment]
From what you post it seems to be a problem related to homebridge-knx plugin. You should contact its developer.
